name: repo_dispatch
on:
    repository_dispatch:
        types: [oussama-event]
jobs:
    example-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print event payload
              run: |
                  echo "Event type: ${{ github.event.action }}"
                  echo "Custom data: ${{ toJson(github.event.client_payload) }}"